//! Coverage of the AsciiDoc language description's *Quotes Substitutions* page.
//!
//! The quotes step replaces inline formatting markup with the corresponding
//! HTML. This crate performs every mapping the page tabulates through
//! `convert`, so the worked example, the AsciiDoc-to-HTML mapping table, and
//! the `quotes`/`q` substitution values are verified. The applicability table
//! is descriptive and tracked as non-normative.

use super::applicability::ran;
use crate::{convert, tests::sdd::*};

track_file!("ref/asciidoc-lang/docs/modules/subs/pages/quotes.adoc");

non_normative!(
    r#"
= Quotes Substitutions
:navtitle: Quotes
:table-caption: Table
:y: Yes
//icon:check[role="green"]
:n: No
//icon:times[role="red"]

"#
);

// The quotes step replaces the formatting marks around inline text with the
// matching HTML tags: a `*…*` pair becomes a `<strong>` element.
#[test]
fn quotes_step() {
    verifies!(
        r#"
The replacement of the formatting markup on inline elements is called the quotes substitution step.

.Syntax input
[source#ex-quotes]
----
Happy werewolves are *really* slobbery.
----

For instance, when a document containing the markup in <<ex-quotes>> is converted to HTML, any asterisks enclosing text are replaced with the start and end tags of the `<strong>` element.
The resulting HTML can be seen in <<ex-html>> below.

.HTML output
[source#ex-html,html]
----
Happy werewolves are <strong>really</strong> slobbery.
----

"#
    );

    let out = convert("Happy werewolves are *really* slobbery.\n");
    assert!(out.contains("Happy werewolves are <strong>really</strong> slobbery."));
}

// Each inline formatting syntax the page tabulates maps to the shown HTML.
#[test]
fn quotes_html_table() {
    verifies!(
        r#"
<<table-quotes-html>> shows the HTML source code that is generated by the quotes substitution step.

.HTML source code generated from AsciiDoc formatting syntax
[#table-quotes-html%autowidth,cols="~,^~,^~"]
|===
|Name |AsciiDoc |HTML

|emphasis
|+_word_+
|<em>word</em>

|strong
|+*word*+
|<strong>word</strong>

|monospace
|+`word`+
|<code>word</code>

|superscript
|+^word^+
|<sup>word</sup>

|subscript
|+~word~+
|<sub>word</sub>

|double curved quotes
|+"`word`"+
|+&#8220;word&#8221;+

|single curved quotes
|+'`word`'+
|+&#8216;word&#8217;+
|===

"#
    );

    assert!(convert("_word_\n").contains("<em>word</em>"));
    assert!(convert("*word*\n").contains("<strong>word</strong>"));
    assert!(convert("`word`\n").contains("<code>word</code>"));
    assert!(convert("^word^\n").contains("<sup>word</sup>"));
    assert!(convert("~word~\n").contains("<sub>word</sub>"));
    assert!(convert("\"`word`\"\n").contains("&#8220;word&#8221;"));
    assert!(convert("'`word`'\n").contains("&#8216;word&#8217;"));
}

non_normative!(
    r#"
== Default quotes substitution

"#
);

// Each row of the applicability table, probed with `*b*`: the quotes step is
// "applied" iff the output wraps it in `<strong>` rather than leaving `*b*`.
#[test]
fn default_quotes_substitution() {
    verifies!(
        r#"
<<table-quotes>> lists the specific blocks and inline elements the quotes substitution step applies to automatically.

.Blocks and inline elements subject to the quotes substitution
[#table-quotes%autowidth,cols="~,^~"]
|===
|Blocks and elements |Substitution step applied by default

|Attribute entry values |{n}

|Comments |{n}

|Examples |{y}

|Literal, listings, and source |{n}

|Macros |{y} +
(except passthrough macros)

|Open |{y}

|Paragraphs |{y}

|Passthrough blocks |{n}

|Quotes and verses |{y}

|Sidebars |{y}

"#
    );

    // `*b*` becomes `<strong>b</strong>` when the quotes step runs.
    let applies = |body: &str| ran("", body, "<strong>");

    // Attribute entry values (no): the value is stored without inline
    // formatting. Isolated with `[subs=attributes]` so the block itself adds no
    // formatting; the stored `*b*` stays literal.
    assert!(!convert(":v: *b*\n[subs=attributes]\n....\n{v}\n....\n").contains("<strong>"));

    // Comments (no): the comment block produces no output.
    assert!(!applies("////\n*b*\n////\n\nsentinel\n"));

    // Examples (yes).
    assert!(applies("====\n*b*\n====\n"));

    // Literal, listings, and source (no).
    assert!(!applies("....\n*b*\n....\n"));
    assert!(!applies("----\n*b*\n----\n"));
    assert!(!applies("[source]\n----\n*b*\n----\n"));

    // Macros (yes): formatting in a macro's text is applied.
    assert!(applies("link:https://example.org[*b*]\n"));

    // Open (yes).
    assert!(applies("--\n*b*\n--\n"));

    // Paragraphs (yes).
    assert!(applies("*b*\n"));

    // Passthrough blocks (no): the raw `*b*` passes straight through.
    assert!(!applies("++++\n*b*\n++++\n"));

    // Quotes and verses (yes).
    assert!(applies("[quote]\n____\n*b*\n____\n"));
    assert!(applies("[verse]\n____\n*b*\n____\n"));

    // Sidebars (yes).
    assert!(applies("****\n*b*\n****\n"));
}

// The table's `Tables` cell is "Varies" (it depends on each cell's format
// specifier), so it is not a single yes/no claim to verify here.
non_normative!(
    r#"
|Tables |Varies

"#
);

// Titles (yes): inline formatting in a block title is applied.
#[test]
fn default_quotes_substitution_titles() {
    verifies!(
        r#"
|Titles |{y}
|===

"#
    );

    assert!(convert(".*b*\n====\nbody\n====\n").contains("<strong>"));
}

non_normative!(
    r#"
[#quotes-value]
== quotes substitution value

"#
);

// For blocks, the step's name `quotes` can be assigned to `subs`; for inline
// text, the built-in values `q` or `quotes` add the step through the inline
// pass macro.
#[test]
fn quotes_value() {
    verifies!(
        r#"
The quotes substitution step can be modified on blocks and inline elements.
For blocks, the step's name, `quotes`, can be assigned to the xref:apply-subs-to-blocks.adoc[subs attribute].
For inline elements, the built-in values `q` or `quotes` can be applied to xref:apply-subs-to-text.adoc[inline text] to add the quotes substitution step.
"#
    );

    // Adding `quotes` to a source block's default group formats the markup that
    // a verbatim block would otherwise leave literal.
    let block = convert("[source,java,subs=\"verbatim,quotes\"]\n----\nSystem.out.println(\"Hello *bold*\")\n----\n");
    assert!(block.contains("Hello <strong>bold</strong>"));

    // The inline `q` shorthand on the pass macro formats the enclosed markup.
    let inline = convert("pass:q[*bold* _em_]\n");
    assert!(inline.contains("<strong>bold</strong> <em>em</em>"));
}
