use clap::Parser as _;

use crate::{run_with_input, tests::sdd::*, Cli};

track_file!("ref/asciidoctor/docs/modules/ROOT/pages/localization-support.adoc");

// Asciidoctor's "Localization Support" page, tracked from the CLI crate. Most
// of the page describes features `adoc` does not implement -- DocBook-toolchain
// label translation, the full table of built-in caption/label attributes, the
// `lang`-driven `locale/attributes.adoc` include, and content translation -- so
// those spans are non-normative here. Three claims have command-line
// counterparts this crate verifies: UTF-8 content passes through unchanged,
// `-a lang=es` is only a hint (it does not translate built-in labels for HTML),
// and `-a version-label=…` retitles the one built-in label `adoc` emits today,
// the revision label in the header. The `asciidoc-html5` crate verifies the
// same three claims through the API, and the sdd tool merges the two crates'
// coverage.

/// Pipes `source` through `adoc` with `args` (which select standard input),
/// returning the captured standalone HTML. Drives the real stdin read path via
/// [`run_with_input`], the injectable-reader core of `run`.
fn run_piped(args: &[&str], source: &str) -> String {
    let cli = Cli::parse_from(args);
    let mut stdin = source.as_bytes();
    let mut stdout = Vec::new();
    run_with_input(&cli, &mut stdin, &mut stdout).expect("adoc converts");
    String::from_utf8(stdout).expect("adoc output is UTF-8")
}

non_normative!(
    r#"
= Localization Support
:keywords: translations, labels, l10n, internationalization, i18n
:url-docbook-i8n: http://www.sagehill.net/docbookxsl/Localizations.html
:url-lang-attributes: {url-org}/asciidoctor/blob/{page-origin-refname}/data/locale/attributes.adoc

"#
);

// UTF-8 content in any language survives conversion unchanged.
#[test]
fn utf8_content_is_rendered_verbatim() {
    verifies!(
        r#"
Asciidoctor is not restricted to working with English-only content.
Asciidoctor can process the full range of the UTF-8 character set.
That means you can write your document in any language, save the file with UTF-8 encoding, and expect Asciidoctor to convert the text properly.

"#
    );

    // A paragraph mixing Latin-with-diacritics, CJK, Greek, and Arabic scripts
    // must appear in `adoc`'s output byte for byte.
    let html = run_piped(
        &["adoc", "-"],
        "Café, naïve, Über. 日本語. Ελληνικά. مرحبا.",
    );
    assert!(html.contains("Café, naïve, Über. 日本語. Ελληνικά. مرحبا."));
}

non_normative!(
    r#"
Furthermore, you can customize the built-in labels (e.g., "`Appendix`") to match the language in which you are writing.
This process is known as localization (l10n).
The built-in labels used in the output generated by Asciidoctor are English by default.
These labels can be modified by changing the value of the <<label-attributes,corresponding attributes>>.

There are some caveats to know about:

* Currently, the official HTML and PDF converters only fully support left-to-right (and top-to-bottom) reading.
Support for right-to-left (RTL) is being considered.
See {url-org}/asciidoctor/issues/1601[issue #1601^] for details.
In the interim, you can leverage the DocBook toolchain to get right-to-left support.
* Attributes that store dates and times (e.g., `docdatetime`) are always formatted like `2019-01-04 19:26:06 -0600`.
* Application messages (i.e., log messages) are always in English.
* Asciidoctor does not support the language conf files used by AsciiDoc.py.
However, Asciidoctor does provide {url-lang-attributes}[a translation file^] that can be used for a similar purpose.

[#customizing-labels]
== Translating built-in labels

When converting to DocBook, you can rely on the DocBook toolchain to translate (most) built-in labels.
To activate this feature, set the `lang` attribute to a valid country code (which defaults to `en` for English).
For example:

 $ asciidoctor -a lang=es -b docbook article.adoc

The list of supported languages, as well as additional language considerations for DocBook, are described in {url-docbook-i8n}[DocBook XSL: The Complete Guide^].

"#
);

// The `lang` attribute is only a hint: `-a lang=es` sets the html `lang` but
// does not translate any built-in label for HTML output.
#[test]
fn lang_does_not_translate_built_in_labels() {
    verifies!(
        r#"
The `lang` attribute _does not_ enable automatic translation of built-in labels when converting directly to HTML or PDF.
It's merely a hint to configure the DocBook toolchain.
If you're not using the DocBook toolchain for publishing, you must translate each built-in label yourself.
One way is to set the following attributes in the document header or by passing the attributes via the API or CLI:

"#
    );

    // `-a lang=es` records the language on the html element, but the built-in
    // revision label stays the English-derived "version" -- no automatic
    // translation happens; the author must set the label attribute themselves.
    let html = run_piped(
        &["adoc", "-a", "lang=es", "-"],
        "= Título\nAutora\nv1.0, 2026-01-04\n",
    );
    assert!(html.contains("<html lang=\"es\">"));
    assert!(html.contains("<span id=\"revnumber\">version 1.0,</span>"));
}

non_normative!(
    r#"
.Attributes that control built-in labels
[#label-attributes,cols="~,~,30%"]
|===
|Attribute |Default English Value |Notes

|`appendix-caption`
|Appendix
|

|`appendix-refsig`
|Appendix
|Used when referencing an appendix.

|`caution-caption`
|Caution
|

|`chapter-signifier`
|Chapter
|Only applies when `doctype` is `book`.

|`chapter-refsig`
|Chapter
|Used when referencing a chapter.

|`example-caption`
|Example
|

|`figure-caption`
|Figure
|

|`important-caption`
|Important
|

|`last-update-label`
|Last updated
|

|`listing-caption`
|_not set_
|By default, listing blocks do not have captions.
Specify `listing-caption` to turn on captions for listing blocks.

|`manname-title`
|NAME
|Only applies when `doctype` is `manpage`.

|`note-caption`
|Note
|

|`part-signifier`
|Part
|

|`part-refsig`
|Part
|Used when referencing a part.

|`preface-title`
|_not set_
|Only applies when `doctype` is `book`.

|`section-refsig`
|Section
|Used when referencing a section.

|`table-caption`
|Table
|

|`tip-caption`
|Tip
|

|`toc-title`
|Table of Contents
|

|`untitled-label`
|Untitled
|

"#
);

// `version-label` is the one built-in label `adoc` emits today: it names the
// revision number in the header (Asciidoctor downcases it). Passing a
// translated value with `-a` changes the rendered label.
#[test]
fn version_label_attribute_translates_the_revision_label() {
    verifies!(
        r#"
|`version-label`
|Version
|

"#
    );

    // `-a version-label=Ausgabe` retitles the revision label; the header renders
    // it downcased, matching Asciidoctor.
    let translated = run_piped(
        &["adoc", "-a", "version-label=Ausgabe", "-"],
        "= Titel\nAutor\nv2.5, 2026-01-04\n",
    );
    assert!(translated.contains("<span id=\"revnumber\">ausgabe 2.5,</span>"));

    // The default value is the English-derived "version".
    let default_html = run_piped(&["adoc", "-"], "= Titel\nAutor\nv2.5, 2026-01-04\n");
    assert!(default_html.contains("<span id=\"revnumber\">version 2.5,</span>"));
}

non_normative!(
    r#"
|`warning-caption`
|Warning
|
|===

If you plan to support multiple languages, you'll want to define the attributes for each language inside a xref:asciidoc:directives:conditionals.adoc[conditional preprocessor directive].
For example:

[,asciidoc]
----
\ifeval::["{lang}" == "de"]
:caution-caption: Achtung
...
\endif::[]
----

Of course, you're probably hoping this has already been done for you.
Indeed, it has!

You can find an {url-lang-attributes}[AsciiDoc file^] in the Asciidoctor repository that provides translations of these attributes for most major languages.
Thus far, the built-in labels have been translated into the following languages: Arabic, Belarusian, Bulgarian, Catalan, Czech, Danish, Dutch, German, Spanish, Persian (Farsi), Finnish, French, Hungarian, Bahasa Indonesian, Italian, Japanese, Korean, Norwegian Bokmål, Norwegian Nynorsk, Polish, Portuguese, Brazilian Portuguese, Romanian, Russian, Serbian Cyrillic, Serbian Latin, Swedish, Turkish, Ukrainian, Vietnamese, Simplified Chinese, and Traditional Chinese.
The translations are defined using AsciiDoc attribute entries inside conditional preprocessor blocks, just as suggested above.

To use this file to translate the built-in labels according the value of the `lang` attribute (just like the DocBook toolchain does), follow these steps:

. Download the AsciiDoc file {url-lang-attributes}[attributes.adoc^] from the Asciidoctor repository.
. Put the file in the folder [.path]_locale_ relative to your document.
. Add the following line to the header of your AsciiDoc document:
+
[,asciidoc]
----
\include::locale/attributes.adoc[]
----

. Set the language using the `lang` attribute.
This attribute must be set before the include directive gets processed.
For example:

 -a lang=es

The built-in labels will now be translated automatically based on the value of the `lang` attribute.

There's an ongoing discussion about how to make language support even simpler ({url-org}/asciidoctor/issues/1129[issue #1129^]).
Input is welcome.

== Translation

Asciidoctor (or DocBook) currently does not support translation of content out of the box.
There's a proposal to integrate gettext (https://discuss.asciidoctor.org/Professional-providers-translating-Asciidoc-tt2692.html#none[discussion^]), and suggestions are welcome.
"#
);
