use std::fs;

use crate::{convert, convert_file, tests::sdd::*};

track_file!("ref/asciidoctor/docs/modules/html-backend/pages/index.adoc");

// Asciidoctor's "Generate HTML from AsciiDoc" page documents the `html`/`html5`
// backend — the default output of Asciidoctor and the exact format this crate
// exists to produce. Unlike the DocBook and man page backend pages (which
// describe formats this crate does not render, so are wholly non-normative),
// this page's core claim is one this crate satisfies: converting an AsciiDoc
// document yields an HTML5 document. This crate verifies that against its API —
// `convert` for the "HTML is the default output" claim and `convert_file` for
// the `asciidoctor my-document.adoc` walkthrough. The `adoc` crate verifies the
// CLI-facing claims (the derived `.html` output name and the `-o -` preview),
// and the sdd tool merges the two crates' coverage.
//
// The rest is non-normative here. The "Backend and converter" facts (the
// converter class, the backend registration) are Asciidoctor internals with no
// counterpart in this crate; the Google Fonts warning is descriptive prose
// about GDPR (the default stylesheet and its web-font link, which this crate
// now embeds, are covered by the default-stylesheet page); and the screenshot
// and CLI-only steps are verified from the `adoc` crate instead. The "Generate
// XHTML" section (and the sentence introducing it) is tracked as non-normative
// by deliberate project decision: this crate emits HTML5 syntax only and does
// not support Asciidoctor's `xhtml`/`xhtml5` backends (see the workspace
// README).

non_normative!(
    r#"
= Generate HTML from AsciiDoc
:navtitle: Generate HTML

"#
);

// The page's opening claim: HTML (specifically HTML 5) is Asciidoctor's default
// output, produced when it runs without any parameters. This crate's API takes
// no backend or output-format parameter at all — `convert` has one behavior,
// and it produces an HTML5 document — so HTML5 is not merely the default output
// here, it is the only output.
#[test]
fn default_output_is_html5() {
    verifies!(
        r#"
Asciidoctor's default output format is HTML (specifically HTML 5).
That means when you run Asciidoctor without any parameters, it will produce HTML.
This page explains how to use Asciidoctor to convert AsciiDoc to HTML.

"#
    );

    let html = convert("= Hello\n\nWorld.");
    assert!(html.starts_with("<!DOCTYPE html>"));
    assert!(html.contains("<title>Hello</title>"));
    assert!(html.contains("<p>World.</p>"));
    assert!(html.trim_end().ends_with("</body>\n</html>"));
}

non_normative!(
    r#"
== Backend and converter

Asciidoctor's built-in HTML converter is registered for the `html` and `html5` backends.
The HTML converter generates HTML 5 that's styled with CSS3.
It may include JavaScript to support additional integrations, such as client-side syntax highlighting.

[horizontal]
Backend names:: `html`, `html5`
Converter class:: `Asciidoctor::Converter::Html5Converter`
Output format:: HTML
Output file extension:: .html

WARNING: A standalone HTML document generated by the built-in HTML converter loads web fonts from Google Fonts, which are then referenced by the default stylesheet.
The xref:default-stylesheet.adoc[default stylesheet] makes use of web fonts to ensure the document renders consistently across platforms.
Concerns have been raised that Google Fonts do not comply with GDPR.
If this presents a problem, you can xref:default-stylesheet.adoc#disable-or-modify-the-web-fonts[opt out of the use of Google Fonts].
When this is done, the default stylesheet reverts to using generic font families (e.g., sans-serif), which are mapped to system fonts by your browser.
The consequence is that the appearance of the document will be different and system dependent due to a reliance on system fonts.

If the backend name is prefixed with `x` (e.g., `xhtml`), the converter will <<xhtml,generate XHTML>>, the XML variant of HTML.

== Generate HTML

In this section, we'll create a sample document, then process and convert it with Asciidoctor's built-in HTML converter.

=== Create and save an AsciiDoc document

. To follow along with the steps below, use your own AsciiDoc file or copy the contents of <<ex-my-doc>> into a new plaintext file.
+
.my-document.adoc
[#ex-my-doc,asciidoc]
----
include::example$my-document.adoc[tags=title;body]
----

. Make sure to save the file with the _.adoc_ file extension.

=== Convert an AsciiDoc document to HTML

To convert [.path]_my-document.adoc_ to HTML from the command line:

. Open a terminal.
. Switch to the directory that contains the [.path]_my-document.adoc_ document
. Call the Asciidoctor processor with the `asciidoctor` command, followed by the name of the document.
+
--
"#
);

// The walkthrough's conversion step: `asciidoctor my-document.adoc` reads the
// file and renders it to HTML5. This crate's closest counterpart is
// `convert_file`, which reads an AsciiDoc file from disk and returns a
// complete, standalone HTML5 document.
#[test]
fn converts_a_file_to_html5() {
    verifies!(
        r#"
 $ asciidoctor my-document.adoc

"#
    );

    // The `title;body` tags of the page's example document — a title, a couple
    // of paragraphs, and a section. Reading it from disk with `convert_file`
    // yields the same complete HTML5 document that `convert` produces for the
    // same source.
    let source = "= The Dangers of Wolpertingers\n\
        :url-wolpertinger: https://en.wikipedia.org/wiki/Wolpertinger\n\n\
        Don't worry about gumberoos or splintercats.\n\
        Something far more fearsome plagues the days, nights, and inbetweens.\n\
        Wolpertingers.\n\n\
        == Origins\n\n\
        Wolpertingers are {url-wolpertinger}[ravenous beasts].\n";
    let path = std::env::temp_dir().join(format!(
        "asciidoc-html5-html-backend-{}.adoc",
        std::process::id()
    ));
    fs::write(&path, source).expect("write temp input");
    let html = convert_file(&path).expect("convert_file reads and renders");
    let _ = fs::remove_file(&path);

    assert_eq!(html, convert(source));
    assert!(html.starts_with("<!DOCTYPE html>"));
    assert!(html.contains("<title>The Dangers of Wolpertingers</title>"));
    assert!(html.trim_end().ends_with("</body>\n</html>"));
}

non_normative!(
    r#"
Remember, Asciidoctor's default converter is html5, so it isn't necessary to specify it with the `-b` command.
--

. You won't see any messages printed to the console.
Type `ls` to view the files in the directory or navigate to the directory in a file manager.
You should see a new file named [.path]_my-document.html_.
+
--
 $ ls
 my-document.adoc  my-document.html

Asciidoctor derives the name of the output document from the name of the input document.
--

. Open [.path]_my-document.html_ in your web browser.
Your document should look like the image below.
+
--
image::my-document.png[]

The document's text, titles, and link are styled by the default Asciidoctor stylesheet, which is embedded in the HTML output.
As a result, you could save [.path]_my-document.html_ to any computer and it will look the same.
--

. If you want to preview the HTML in the terminal, you can use this command instead:

 $ asciidoctor my-document.adoc -o - | w3m - -T text/html

[#xhtml]
== Generate XHTML

[horizontal]
Backend names:: `xhtml`, `xhtml5`
Converter class:: `Asciidoctor::Converter::Html5Converter`
Output format:: XML variant of HTML
Output file extension:: .html

.Produce XHTML using the xhtml5 backend option
 $ asciidoctor -b xhtml5 my-document.adoc

To produce XHTML instead of HTML when using converter templates, set the `htmlsyntax` attribute to `xml` in addition to the backend option:

.Produce XHTML using custom templates
 $ asciidoctor -T /path/to/templates -b slides -a htmlsyntax=xml my-document.adoc

.Black Box Decoded: XHTML and htmlsyntax
****
XHTML output is a special mode of the built-in HTML5 converter.
It is activated by prefixing the backend value with `x` (e.g., `xhtml` or `xhtml5`).
This hint implicitly assigns the `htmlsyntax` attribute to the value `xml`, which normally has the value `html`.

For all other converters, the `htmlsyntax` attribute is not set explicitly.
If you want a converter template that's written in Slim or Haml to output XHTML instead of the default HTML, you need to set the `htmlsyntax` attribute to `xml` explicitly.
Asciidoctor will pass on this preference to the Slim or Haml template engine by setting the `:format` option to `:html5`.
****
"#
);
