use crate::tests::sdd::*;

// These tests assert the standalone document shell (the Font Awesome
// stylesheet `<link>` lives in `<head>`), so they render in standalone mode
// explicitly. The string entry points default to embedded, body-only output.
fn convert_with(source: &str, options: &crate::Options) -> String {
    crate::convert_with(source, &options.clone().standalone(true))
}

track_file!("ref/asciidoctor/docs/modules/html-backend/pages/local-font-awesome.adoc");

// Asciidoctor's "Use Local Font Awesome" page. It documents the
// `iconfont-remote` and `iconfont-name` attributes that control where the
// Font Awesome stylesheet `<link>` (emitted under `:icons: font`) points.
//
// The verifiable claims are the two `<link>` forms this crate's `iconfont_head`
// emits: the default CDN link (`iconfont-remote` set, the default) and the
// local link resolved against `stylesdir` (`iconfont-remote` unset), with and
// without a custom `iconfont-name`. The asset-download instructions and the
// warning about relocating the stylesheet without `stylesdir` are file-system
// prose with no counterpart in this string-to-string library.
//
// Tracked from the library crate only: every verifiable claim is about the
// `<link>` this crate's HTML `<head>` carries. Where the page drives behavior
// with a CLI `-a` attribute, we supply the same attribute through `Options`;
// the `adoc -a` option is a thin forwarder onto that API, covered by the CLI
// crate's own tests.

non_normative!(
    r#"
= Use Local Font Awesome

When font-based icons are enabled, the HTML converter configures the HTML document to retrieve the Font Awesome assets (CSS and fonts) from a CDN.
This default behavior provides a convenience for users who want the visual enhancement of font-based icons without having to do any extra steps.
There are valid concerns with linking directly to a CDN, especially one that's outside your organization.
Asciidoctor provides a way to point to a local copy of Font Awesome instead.

In this guide, we'll assume that you've already enabled font-based icons on your document (i.e., set the `icons` attribute in your document to the value `font`).

== Prepare the Font Awesome assets

The first thing you'll need to do is download a copy of https://fontawesome.com/v4/get-started/[Font Awesome].
The HTML converter currently integrates with Font Awesome 4, so make sure you're using that version.

"#
);

// The page states the HTML converter integrates with Font Awesome 4 — this
// crate's CDN link names the same version, `FONT_AWESOME_VERSION` (`4.7.0`).
#[test]
fn the_default_link_points_at_the_font_awesome_4_cdn() {
    verifies!(
        r#"
Extract the zip file and arrange the Font Awesome assets into the location of the output file (i.e., the HTML file generated by Asciidoctor) as follows:

....
css/font-awesome.css
fonts/fontawesome-webfont.eot
fonts/fontawesome-webfont.svg
fonts/fontawesome-webfont.ttf
fonts/fontawesome-webfont.woff
fonts/fontawesome-webfont.woff2
....

"#
    );

    non_normative!(
        r#"
It's important that these files are located in the same directory as the output file.
If that's the same directory where the AsciiDoc file is located, then you're already set.

== Switch to your local Font Awesome assets

Now that you've set up Font Awesome locally, you'll need to instruct Asciidoctor to use it instead of the one from the CDN.
The key attribute that controls this behavior is `iconfont-remote`.
"#
    );

    verifies!(
        r#"
But default, this attribute is set.
"#
    );

    // With `icons=font` and nothing else, `iconfont-remote` is set (the
    // default), so the `<link>` points at the Font Awesome 4 CDN.
    let html = convert_with(
        "= Doc\n\ntext",
        &crate::Options::new().attribute("icons", "font"),
    );
    assert!(html.contains(
        "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">"
    ));
}

// Unsetting `iconfont-remote` and setting `stylesdir` makes the `<link>` point
// at a local Font Awesome stylesheet resolved against `stylesdir` instead of
// the CDN.
#[test]
fn unsetting_iconfont_remote_links_the_local_stylesheet() {
    verifies!(
        r#"
If you unset this attribute (e.g., `-a iconfont-remote!`), Asciidoctor will look for the Font Awesome stylesheet in the `stylesdir`.
We'll assume that you're setting the `stylesdir` attribute to the value `css`.
If you have a custom stylesheet, it should be located in that folder as well.

Here's what the call looks like with these attributes configured:

 $ asciidoctor -a stylesdir=css -a iconfont-remote! doc.adoc

"#
    );

    // The page sets both attributes from the CLI (`-a stylesdir=css
    // -a iconfont-remote!`); we supply them the same way through `Options`, the
    // API the `adoc -a` option feeds.
    let html = convert_with(
        "= Doc\n\ntext",
        &crate::Options::new()
            .attribute("icons", "font")
            .unset("iconfont-remote")
            .attribute("stylesdir", "css"),
    );

    // This crate's `<link>` resolves the local stylesheet against `stylesdir`
    // the way it resolves every other stylesheet path — with the `./` prefix
    // `normalize_web_path` always adds to a relative result. The page's
    // `<link>` snippet below omits that prefix, so it stays non-normative.
    assert!(html.contains("<link rel=\"stylesheet\" href=\"./css/font-awesome.css\">"));

    non_normative!(
        r#"
This will configure the HTML to reference Font Awesome as follows:

[,html]
----
<link rel="stylesheet" href="css/font-awesome.css">
----

WARNING: The Font Awesome stylesheet assumes the fonts are located in a directory named [.path]_fonts_ adjacent to the directory containing the stylesheet (i.e., [.path]_../fonts_).
Therefore, if you don't set the `stylesdir` attribute, and you move [.path]_font-awesome.css_ to the directory containing the output file, the Font Awesome stylesheet will look in the wrong location for the fonts and the icons won't work.
To fix the problem, you can edit [.path]_font-awesome.css_ and adjust the path to the fonts (e.g., change the prefix to [.path]_fonts_ instead of [.path]_../fonts_).

"#
    );
}

// The `iconfont-name` attribute overrides the local stylesheet's basename.
#[test]
fn iconfont_name_overrides_the_local_stylesheet_basename() {
    verifies!(
        r#"
If you rename the Font Awesome stylesheet to something other than [.path]_font-awesome.css_, you can tell the HTML converter which basename to use by setting the `iconfont-name` attribute.
Let's assume that you have set up your Font Awesome assets as follows:

....
css/fa.css
fonts/fontawesome-webfont.eot
fonts/fontawesome-webfont.svg
fonts/fontawesome-webfont.ttf
fonts/fontawesome-webfont.woff
fonts/fontawesome-webfont.woff2
....

You then pass the modified basename of the stylesheet using the following call:

 $ asciidoctor -a stylesdir=css -a iconfont-remote! -a iconfont-name=fa doc.adoc

"#
    );

    let html = convert_with(
        "= Doc\n\ntext",
        &crate::Options::new()
            .attribute("icons", "font")
            .unset("iconfont-remote")
            .attribute("stylesdir", "css")
            .attribute("iconfont-name", "fa"),
    );
    assert!(html.contains("<link rel=\"stylesheet\" href=\"./css/fa.css\">"));
}

non_normative!(
    r#"
If you want to change the name of the fonts directory, or you want to configure the Font Awesome stylesheet to only attempt to load one of the fonts, you'll need to modify the stylesheet directly.

TIP: You can use these same attributes to integrate a different icon font library, though it must work in the same way as Font Awesome.
"#
);
