= Paragraphs

The primary block type in most documents is the paragraph.
That's why in AsciiDoc, you don't need to use any special markup or attributes to create paragraphs.
You can just start typing sentences and that content becomes a paragraph.

This page introduces you to the paragraph in AsciiDoc and explains how to set it apart from other paragraphs.

== Create a paragraph

Adjacent or consecutive lines of text form a paragraph element.
To start a new paragraph after another element, such as a section title or table, hit the kbd:[RETURN] key twice to insert an empty line, and then continue typing your content.

.Two paragraphs in an AsciiDoc document
[#ex-paragraph]
----
include::example$paragraph.adoc[tag=para]
----

The result of <<ex-paragraph>> is displayed below.

====
include::example$paragraph.adoc[tag=para]
====

[#block-attribute-line-conflict]
== Conflict with a block attribute line

The first line of a paragraph cannot start with `[` and end with `]`.
That's because it will be treated as block metadata, specifically a block attribute line.

There are two ways to work around this issue.
First, you can add any text in front of the `[` that will otherwise not be rendered to disrupt the syntax match.
For example, you can start the paragraph with the attribute reference `+{empty}+`.

----
{empty}[.rolename]*main text*footnote:[The footnote.]
----

Another way to solve the problem is to write the paragraph as a literal paragraph, then override the implicit style using the explicit style normal.

----
[normal]
 [.rolename]*main text*footnote:[The footnote.]
----

The normal style often comes in handy when you want to prevent the parser from matching beginning-of-line syntax.
