//! Coverage of the AsciiDoc language description's *Assign Custom IDs and
//! Reference Text* page.
//!
//! The page describes assigning a custom ID and optional reference text to a
//! section, and registering auxiliary inline anchors on a section title. The
//! verifiable rendering rules – the custom-ID shorthand, the ID-plus-reftext
//! shorthand and its block-anchor equivalent (driven through an unlabeled
//! xref), and auxiliary inline anchors at the beginning, at the end, and
//! alongside an explicit primary ID – are checked through `convert`. The
//! descriptive prose and the reftext-quoting, XML-Name, UTF-8/a2x, and
//! "auxiliary IDs are not registered" notes are tracked non-normative.

use crate::{
    convert,
    tests::{assert_html::assert_css, sdd::*},
};

track_file!("ref/asciidoc-lang/docs/modules/sections/pages/custom-ids.adoc");

// Page title, document attribute, and the descriptive introduction to custom
// IDs and reference text carry no rule of their own.
non_normative!(
    r#"
= Assign Custom IDs and Reference Text
:url-adoc-a2x: https://aerostitch.github.io/misc/asciidoc/asciidoc-title_uft8.html

You can assign a custom ID and optional reference text (i.e., label) to a section (see xref:attributes:id.adoc#anchor[anchor]).
The custom ID is used in place of the autogenerated ID.
This can be useful when you want to define a stable anchor for linking to a section using a cross reference.
The reference text is used when referencing the ID without specifying explicit text.
This is a good way to centrally manage the automatic reference text that is used to refer to a section.

"#
);

// The custom-ID shorthand `[#id]` puts that ID on the section heading in place
// of the autogenerated one.
#[test]
fn custom_id_shorthand() {
    verifies!(
        r#"
Here's an example of a section with a custom ID:

[source]
----
include::example$section.adoc[tag=with-anchor-shorthand]
----

"#
    );

    // The included `with-anchor-shorthand` tag is the two literal lines driven
    // here; the custom ID lands verbatim on the `<h3>`.
    let html = convert("[#tigers-subspecies]\n=== Subspecies of Tiger");

    assert_css(&html, "h3#tigers-subspecies", 1);
}

// The `[#id,reftext=…]` shorthand assigns both the custom ID and the reference
// text used when an xref names the ID without explicit link text.
#[test]
fn custom_id_and_reftext_shorthand() {
    verifies!(
        r#"
Here's an example of a section with a custom ID and reference text:

[source]
----
include::example$section.adoc[tag=with-anchor-and-reftext-shorthand]
----

"#
    );

    // A preceding unlabeled xref resolves to the section's reference text, so the
    // link's visible text is "Subspecies", not the section title.
    let html = convert(
        "See <<tigers-subspecies>>.\n\n[#tigers-subspecies,reftext=Subspecies]\n=== Subspecies of Tiger",
    );

    assert_css(&html, r##"a[href="#tigers-subspecies"]"##, 1);
    assert!(html.contains(r##"<a href="#tigers-subspecies">Subspecies</a>"##));
}

// The reftext-quoting rule is a descriptive authoring note, not an output rule.
non_normative!(
    r#"
IMPORTANT: The value of the reftext attribute must be quoted if it contains spaces or commas.

"#
);

// The block-anchor form `[[id,reftext]]` assigns the same custom ID and
// reference text, so an unlabeled xref renders identically to the shorthand.
#[test]
fn custom_id_and_reftext_block_anchor() {
    verifies!(
        r#"
The ID and reference text can also be defined using the block anchor syntax:

[source]
----
include::example$section.adoc[tag=with-anchor-and-reftext]
----

"#
    );

    // The `[[tigers-subspecies,Subspecies]]` block anchor sets both ID and
    // reference text; the unlabeled xref again renders as "Subspecies".
    let html = convert(
        "See <<tigers-subspecies>>.\n\n[[tigers-subspecies,Subspecies]]\n=== Subspecies of Tiger",
    );

    assert!(html.contains(r##"<a href="#tigers-subspecies">Subspecies</a>"##));
}

// The XML-Name constraint on block-anchor IDs and the UTF-8/a2x portability
// note are descriptive authoring guidance, not output rules.
non_normative!(
    r#"
When using the block anchor syntax, the ID must conform to the https://www.w3.org/TR/REC-xml/#NT-Name[XML Name] rules, which means the ID must start with a letter, an underscore, or a colon.

IMPORTANT: AsciiDoc allows all valid UTF-8 characters to be used in section IDs.
If you're generating a PDF from AsciiDoc using a2x and dblatex, see {url-adoc-a2x}[Using UTF-8 titles with a2x] to learn about the required `latex.encoding=utf8` switch to activate this portability.

"#
);

// The section heading and the descriptive introduction to auxiliary IDs carry
// no rule of their own.
non_normative!(
    r#"
== Assign auxiliary IDs

A section title can only have a single primary ID.
However, it's possible to register auxiliary IDs on a section title for referencing from the URL using inline anchors.
This feature works regardless of whether you assign an explicit (primary) ID.

CAUTION: If possible, you should avoid adding inline anchors on a section title.
However, if you need to be able to link to that section from a URL using alternate fragment identifiers, this is what you need to use.

"#
);

// Inline anchors on a section title become empty `<a id>` anchors placed where
// they appear (beginning or end), and they coexist with an explicit primary ID
// that stays on the heading element.
#[test]
fn auxiliary_ids() {
    verifies!(
        r#"
Here's how to register auxiliary IDs using inline anchors when using an autogenerated ID:

.Register auxiliary IDs at the beginning of the section title
[source]
----
== [[secondary-id]][[tertiary-id]]Section Title
----

.Register auxiliary IDs at the end of the section title
[source]
----
== Section Title[[secondary-id]][[tertiary-id]]
----

Where you place the inline anchor is where the anchor will end up in the output.
The beginning is the preferred location.

These additional anchor points don't interfere with the declaration of the primary ID, as shown in the next example.

.Register auxiliary IDs on a section title with an explicit ID
[source]
----
[#primary-id]
== [[secondary-id]][[tertiary-id]]Section Title
----

"#
    );

    // Anchors at the beginning precede the title text inside the autogenerated
    // heading.
    let begin = convert("== [[secondary-id]][[tertiary-id]]Section Title");

    assert!(begin.contains(
        r#"<h2 id="_section_title"><a id="secondary-id"></a><a id="tertiary-id"></a>Section Title</h2>"#
    ));

    // Anchors at the end follow the title text – the anchor lands where it is
    // placed in the source.
    let end = convert("== Section Title[[secondary-id]][[tertiary-id]]");

    assert!(end.contains(
        r#"<h2 id="_section_title">Section Title<a id="secondary-id"></a><a id="tertiary-id"></a></h2>"#
    ));

    // An explicit primary ID stays on the heading element while the auxiliary
    // anchors remain inside it.
    let explicit = convert("[#primary-id]\n== [[secondary-id]][[tertiary-id]]Section Title");

    assert!(explicit.contains(
        r#"<h2 id="primary-id"><a id="secondary-id"></a><a id="tertiary-id"></a>Section Title</h2>"#
    ));
}

// This is a negative behavioral claim (auxiliary IDs are not registered with
// the referencing system) that would only be testable through a brittle absence
// assertion, so it is tracked non-normative.
non_normative!(
    r#"
IMPORTANT: These auxiliary IDs are not registered with the referencing system.
That means they cannot be used for referencing the section title within the document.
They are only intended for assigning auxiliary fragment identifiers to the section title so it can be referenced the from the URL using a URL fragment (aka deep linking).
Only the primary ID can be used for referencing the section title within the document.
"#
);
