//! Coverage of the AsciiDoc language description's *Image Icons Mode* page.
//!
//! With `icons` set to `image` (or empty), this crate resolves both admonition
//! icons and the icon macro to `<img>` elements under the `iconsdir` directory,
//! with the `icontype` extension. The default directory (`./images/icons`), the
//! default extension (`.png`), and the `iconsdir`/`icontype` overrides are all
//! verified through `convert`.
//!
//! Note on `imagesdir`: the AsciiDoc language spec (and `asciidoc-parser`) make
//! the default `iconsdir` relative to `imagesdir` (`{imagesdir}/icons`).
//! Asciidoctor 2.0.26 instead keeps a fixed `./images/icons` regardless of
//! `imagesdir`, so this crate diverges from the oracle in that one case; the
//! tests below exercise the (oracle-matching) default and explicit-override
//! cases.

use crate::{convert_with, tests::sdd::*, Options, SafeMode};

track_file!("ref/asciidoc-lang/docs/modules/macros/pages/icons-image.adoc");

// These examples enable icons from the *document* header (`:icons:` / `:icons:
// image`), which only takes effect below the `Secure` safe mode: under `Secure`
// (the API default) Asciidoctor drops a document-set `icons` so an untrusted
// document cannot steer icon image sources through `iconsdir` (see #56). They
// therefore convert under `Server` — the highest mode that still lets the
// document enable icons — matching the image-icon output the page documents.
fn convert(source: &str) -> String {
    convert_with(source, &Options::new().safe_mode(SafeMode::Server))
}

non_normative!(
    r#"
= Image Icons Mode

Setting the `icons` attribute to `image` (or leaving it empty) instructs the AsciiDoc processor to use images for icons.
This page defines where the processor looks for these image files by default, which image file extension it prepends, and how to configure both.

"#
);

// Setting `icons` to `image` (or empty) selects image mode: both the icon macro
// and admonition icons render as `<img>` elements. Image mode influences only
// the converted output, not parsing.
#[test]
fn enable_image_based_icons() {
    verifies!(
        r#"
== Enable image-based icons

To enable image-based icons, you set the `icons` attribute in the document header to the value `image`.

[source]
----
= Document Title
:icons: image
----

This setting has no affect on the parsing of the AsciiDoc document.
It only influences the output generated by the converters.

"#
    );

    // `icons: image` resolves an icon macro to an `<img>` element.
    assert!(convert(":icons: image\n\nicon:tags[]")
        .contains(r#"<span class="icon"><img src="./images/icons/tags.png" alt="tags"></span>"#));

    // Leaving `icons` empty selects the same image mode.
    assert!(convert(":icons:\n\nicon:tags[]")
        .contains(r#"<span class="icon"><img src="./images/icons/tags.png" alt="tags"></span>"#));

    // An admonition's icon cell resolves to an `<img>` in image mode, too.
    assert!(convert(":icons: image\n\nNOTE: x")
        .contains(r#"<img src="./images/icons/note.png" alt="Note">"#));
}

// With neither `iconsdir` nor `imagesdir` configured, icons resolve under the
// default `./images/icons` directory with the `.png` extension.
#[test]
fn default_icons_directory_and_type() {
    verifies!(
        r#"
== Default icons directory and type

By default, the AsciiDoc processor will look for icons in the [.path]_icons_ directory relative to the value of the `imagesdir` attribute.
If you have not configured either attribute, that path resolves to [.path]_./images/icons_.

The processor won't look for icons of any type (i.e., format).
Instead, it will look for icons that have the _.png_ file extension.

"#
    );

    // "If you have not configured either attribute": the default resolves to
    // `./images/icons/<name>.png`.
    assert!(convert(":icons: image\n\nicon:note[]")
        .contains(r#"<img src="./images/icons/note.png" alt="note">"#));
}

// The admonition example resolves the same default path for an admonition
// block's icon cell.
#[test]
fn default_admonition_icon_path() {
    verifies!(
        r#"
Let's assume you have the following NOTE admonition block in your document:

[source]
----
NOTE: Remember the milk!
----

The AsciiDoc processor will resolve the admonition icon to [.path]_./images/icons/note.png_.

"#
    );

    assert!(convert(":icons: image\n\nNOTE: Remember the milk!")
        .contains(r#"<img src="./images/icons/note.png" alt="Note">"#));
}

// An explicit `iconsdir` changes where icons are resolved.
#[test]
fn configure_iconsdir() {
    verifies!(
        r#"
== Configure the icons directory using iconsdir

To change where the AsciiDoc processor looks for icons, you can specify a different location using the `iconsdir` attribute.

For example:

[source]
----
= Document Title
:icons: image
:iconsdir: icons
----

When converting this document, the AsciiDoc processor will look for images in the [.path]_icons_ directory instead of the default [.path]_./images/icons_.

"#
    );

    // With `iconsdir` set to `icons`, both the icon macro and an admonition icon
    // resolve under that directory instead of the default `./images/icons`.
    assert!(convert(":icons: image\n:iconsdir: icons\n\nicon:note[]")
        .contains(r#"<img src="icons/note.png" alt="note">"#));
    assert!(convert(":icons: image\n:iconsdir: icons\n\nNOTE: x")
        .contains(r#"<img src="icons/note.png" alt="Note">"#));
}

// The `icontype` attribute sets the extension used when the icon type must be
// inferred (an admonition icon, or an icon-macro target without an extension).
#[test]
fn configure_icontype() {
    verifies!(
        r#"
== Configure the icon type using icontype

If the icon path is derived, such as for an admonition icon or if the target of the icon macro does not have a file extension, the AsciiDoc processor will use the `icontype` attribute to determine which image type (i.e., format) to look for.
By default, the value of this attribute is `png`, so the processor will look for an image with the file extension `.png`.

You can use the `icontype` document attribute to configure the default icon type.

For example:

[source]
----
= Document Title
:icons: image
:icontype: svg
----

"#
    );

    // By default the derived extension is `.png`.
    assert!(convert(":icons: image\n\nicon:heart[]")
        .contains(r#"<img src="./images/icons/heart.png" alt="heart">"#));

    // Setting `icontype` to `svg` changes the derived extension to `.svg`.
    assert!(convert(":icons: image\n:icontype: svg\n\nicon:heart[]")
        .contains(r#"<img src="./images/icons/heart.svg" alt="heart">"#));
}

// The derived extension applies to admonition icons, too.
#[test]
fn icontype_applies_to_admonition_icons() {
    verifies!(
        r#"
For NOTE admonitions, the AsciiDoc processor will now look for the image [.path]_note.svg_ in the `iconsdir` instead of [.path]_note.png_.

"#
    );

    assert!(convert(":icons: image\n:icontype: svg\n\nNOTE: x")
        .contains(r#"<img src="./images/icons/note.svg" alt="Note">"#));
}

// The `icontype` extension is only appended when the type must be inferred; an
// icon-macro target that already carries an extension is used verbatim.
#[test]
fn icontype_ignored_when_target_has_extension() {
    verifies!(
        r#"
The value of the `icontype` attribute is ignored for the icon macro if the target has a file extension.
It's only used when the icon type must be inferred.
"#
    );

    assert!(convert(":icons: image\n:icontype: svg\n\nicon:heart.png[]")
        .contains(r#"<img src="./images/icons/heart.png" alt="heart">"#));
}
