//! Coverage of the AsciiDoc language description's *Font Icons Mode* page.
//!
//! With `icons` set to `font`, this crate resolves the icon macro to a Font
//! Awesome glyph (`<i class="fa fa-<name>">`) and an admonition's icon cell to
//! the admonition's CSS class (`<i class="fa icon-<name>" title="<Label>">`),
//! matching Asciidoctor 2.0.26. Those converter behaviors are verified through
//! `convert`. The default-font choice, the recommended font-glyph mappings, the
//! stylesheet/CSS details, and the callout styling are runtime/stylesheet
//! concerns tracked as non-normative (including the page's `////` comment
//! block).

use crate::{convert_with, tests::sdd::*, Options, SafeMode};

track_file!("ref/asciidoc-lang/docs/modules/macros/pages/icons-font.adoc");

// These examples enable icons from the *document* header (`:icons: font`),
// which only takes effect below the `Secure` safe mode: under `Secure` (the API
// default) Asciidoctor drops a document-set `icons` so an untrusted document
// cannot steer icon image sources through `iconsdir` (see #50). They therefore
// convert under `Server` — the highest mode that still lets the document enable
// icons — matching the font-icon output the page documents.
fn convert(source: &str) -> String {
    convert_with(source, &Options::new().safe_mode(SafeMode::Server))
}

non_normative!(
    r#"
= Font Icons Mode
:url-fontawesome-icons: https://fontawesome.com/v4/icons/

Setting the `icons` attribute to `font` instructs the AsciiDoc processor to select icons from an icon font.

CAUTION: Not all converters support this mode.
If a converter does not support this mode, it will fall back to the xref:icons-image.adoc[image mode].

"#
);

// Setting `icons` to `font` selects an icon-font glyph for the icon macro,
// influencing only the converted output, not parsing.
#[test]
fn enable_font_based_icons() {
    verifies!(
        r#"
== Enable font-based icons

To enable image-based icons, you set the `icons` attribute in the document header to the value `font`.

[source]
----
= Document Title
:icons: font
----

This setting has no affect on the parsing of the AsciiDoc document.
It only influences the output generated by the converters.

"#
    );

    // `icons: font` selects a Font Awesome glyph (`<i class="fa fa-<name>">`) for
    // the icon macro.
    assert!(convert(":icons: font\n\nicon:heart[]")
        .contains(r#"<span class="icon"><i class="fa fa-heart"></i></span>"#));

    // The attribute has no affect on parsing: the same source without it still
    // parses to a paragraph (only the rendered output would differ).
    assert!(convert("icon:heart[]").contains(r#"<div class="paragraph">"#));
}

// The default-font choice, the recommended font-glyph mappings' online access,
// and the stylesheet requirement are processor/runtime concerns.
non_normative!(
    r#"
IMPORTANT: When converting to HTML, the stylesheet is required in order for the font-based icons to work.

== Default icon font

The icon font that is used by default is determined by the processor.
Asciidoctor, for example, uses the Font Awesome icon font.
You can see the available icons in Font Awesome on the {url-fontawesome-icons}[Font Awesome icons page^].
Using the Font Awesome icons in Asciidoctor requires online access by default.

"#
);

// The processor maps each admonition to a CSS class (`icon-<name>`); the
// stylesheet then maps that class to a Font Awesome glyph. The recommended
// glyph mappings (note -> info-circle, …) are a stylesheet concern, but the
// converter markup — the `icon-<name>` class the mapping keys off — is verified
// here for all five built-in admonition types.
#[test]
fn default_admonition_icon_css_classes() {
    verifies!(
        r#"
== Default admonition icons

Since the names of admonitions doesn't necessarily match the names of icons in the icon font, the AsciiDoc processor must map admonition CSS classes to icon names.

When using Font Awesome as the icon set, the following mappings are recommended:

* note -> info-circle
* tip -> lightbulb-o
* warning -> warning
* caution -> fire
* important -> exclamation-circle

"#
    );

    // Each built-in admonition, in font mode, renders `<i class="fa icon-<name>"
    // title="<Label>">` — the CSS class the stylesheet maps to a glyph.
    for (style, name, label) in [
        ("NOTE", "note", "Note"),
        ("TIP", "tip", "Tip"),
        ("WARNING", "warning", "Warning"),
        ("CAUTION", "caution", "Caution"),
        ("IMPORTANT", "important", "Important"),
    ] {
        let output = convert(&format!(":icons: font\n\n{style}: x"));
        assert!(
            output.contains(&format!(
                r#"<i class="fa icon-{name}" title="{label}"></i>"#
            )),
            "font-mode {style} admonition should emit icon-{name}; got:\n{output}"
        );
    }
}

// The `////` block is commented-out TODO content (not rendered); it documents
// the font-based admonition markup and the stylesheet CSS classes, both of
// which are exercised by `default_admonition_icon_css_classes` above.
non_normative!(
    r#"
////
TODO: move to Asciidoctor

== Default font-based admonition icons

When font-based icons are enabled, Asciidoctor will draw the icons for the 5 built-in admonition types using Font Awesome.
To use the default font-based admonition icons for admonitions, set the value of the `icons` document attribute to `font` in the document header.

[source]
----
= Document Title
:icons: font

NOTE: Asciidoctor supports font-based admonition icons, powered by Font Awesome!
----

// We need to explain that the default admonition icons have different names (i.e., `icon-note` instead of `fa-note`, because they're built in to the stylesheet.

Asciidoctor will emit HTML markup that selects the appropriate font character from the Font Awesome font for each admonition block.
For instance, Asciidoctor selects the Font Awesome icon `icon-note` for `NOTE` admonition blocks.

.Result: HTML output when the icons attribute is set to font
[source,html]
----
<div class="admonitionblock note">
<table>
<tr>
<td class="icon">
<i class="fa icon-note" title="Note"></i>
</td>
<td class="content">
Asciidoctor supports font-based admonition icons, powered by Font Awesome!
</td>
</tr>
</table>
</div>
----

This is how the admonition looks rendered.

NOTE: Asciidoctor supports font-based admonition icons, powered by Font Awesome!

The icons chosen are selected by the stylesheet.
The default stylesheet maps icons to the following 5 CSS classes:

* .admonitionblock td.icon .icon-note
* .admonitionblock td.icon .icon-tip
* .admonitionblock td.icon .icon-warning
* .admonitionblock td.icon .icon-caution
* .admonitionblock td.icon .icon-important

If you want to customize the icon or the color that is used, you'll need to provide a custom stylesheet or override the styles using a docinfo file.
Here's an example that shows how to change the icon for the note admonition to sticky note:

[source,css]
----
.admonitionblock td.icon .icon-note::before {
  content: "\f24a";
  color:black;
}
----
////

"#
);

// Callout numbers in font mode are styled with CSS (the icon font is not used),
// so there is no font-specific converter markup to verify beyond the ordinary
// callout rendering covered on the *Callouts* page.
non_normative!(
    r#"
== Callout numbers and font icon mode

In the font icon mode, xref:verbatim:callouts.adoc[callout numbers] are displayed as enclosed numbers.
However, the icon font is not used to render these glyphs.
Instead, they are styled this way using CSS.
This is done to allow the range of callout numbers to be open-ended.
"#
);
