//! Coverage of the AsciiDoc language description's *Automatic Table of
//! Contents* page.
//!
//! Setting the `toc` document attribute enables the autogenerated table of
//! contents. Matching Asciidoctor 2.0.26, this crate renders it – by default –
//! as a `<div id="toc" class="toc">` inside the document header, titled
//! _Table of Contents_, listing level-1 and level-2 section titles only. The
//! activation, default title, default position, and default depth are verified
//! through `convert`; the illustrative screenshots and cross-references to the
//! customization pages are non-normative.
//!
//! The page draws its example document with `include::example$toc.adoc`
//! directives; the tests reproduce the relevant tagged snippets inline.

use crate::{
    convert_with,
    tests::{
        assert_html::{assert_css, assert_xpath},
        sdd::*,
    },
    Options,
};

track_file!("ref/asciidoc-lang/docs/modules/toc/pages/index.adoc");

// The `tag=header` and `tag=body` snippets from `example$toc.adoc`, assembled
// with a `:toc:` attribute entry between them, exactly as `<<ex-default>>`
// shows (a title, three authors, the `toc` attribute, then four nested
// sections).
const WITH_TOC: &str = "\
= The Intrepid Chronicles
Kismet Lee; B. Steppenwolf; Pax Draeke
:toc:

== Certain Peril

Daylight trickles across the cobblestones...

=== A Recipe for Potion

We have to harvest the leaves by the light of the teal moons...

==== Searching for Ginseng

Crawling through the twisted understory...

== Dawn on the Plateau

Hanging from...
";

// The same document without the `:toc:` attribute entry, used to show that the
// attribute alone (however it is set) is what activates the TOC.
const WITHOUT_TOC: &str = "\
= The Intrepid Chronicles
Kismet Lee; B. Steppenwolf; Pax Draeke

== Certain Peril

Daylight trickles across the cobblestones...

=== A Recipe for Potion

We have to harvest the leaves by the light of the teal moons...

==== Searching for Ginseng

Crawling through the twisted understory...

== Dawn on the Plateau

Hanging from...
";

// Renders a standalone document, so the header, TOC, and its placement are
// present in the output (the string entry points default to embedded output).
fn convert(source: &str) -> String {
    crate::convert_with(source, &Options::new().standalone(true))
}

// The document title and the conceptual introduction: what a TOC is and that
// its depth is configurable. Descriptive prose with nothing to render.
non_normative!(
    r#"
= Automatic Table of Contents

A table of contents (TOC) is an index of section titles in an AsciiDoc document.
When the TOC is enabled, the AsciiDoc processor automatically generates the TOC from the document's structure and inserts it into the output document.
The number of levels (i.e., depth) of the TOC is configurable.

"#
);

// Setting the `toc` document attribute activates the autogenerated TOC. With
// `:toc:` in the header, `convert` emits a `<div id="toc">` carrying the nested
// section outline.
#[test]
fn toc_attribute_activates_the_toc() {
    verifies!(
        r#"
== Activate the TOC

To enable the autogenerated TOC, set the `toc` document attribute.
The `toc` attribute is activated with an attribute entry in the document header.

.Enable TOC with the toc attribute
[source#ex-default]
----
include::example$toc.adoc[tag=header]
:toc: <.>
include::example$toc.adoc[tag=body]
----
<.> Set the `toc` attribute in the header using an attribute entry.
When the value of `toc` is empty, the processor will use the attribute's default value.

"#
    );

    let output = convert(WITH_TOC);
    assert_css(&output, r#"div#toc"#, 1);
    assert_xpath(&output, r#"//div[@id="toc"]/ul[@class="sectlevel1"]"#, 1);
}

// The default rendering claims: an empty-valued `toc` places the TOC directly
// below the document header, titles it _Table of Contents_, and lists level-1
// and level-2 section titles only (`toclevels` defaults to 2). The document's
// level-3 section (`==== Searching for Ginseng`) is therefore absent from the
// TOC, so no `ul.sectlevel3` is emitted.
#[test]
fn default_toc_is_in_the_header_titled_and_two_levels_deep() {
    verifies!(
        r#"
By default, the TOC is rendered directly below the document header, is titled _Table of Contents_, and contains section 1 and section 2 level titles only.
The result of <<ex-default>> is displayed below.

"#
    );

    let output = convert(WITH_TOC);

    // Directly below the document header: the TOC div is a descendant of the
    // header div.
    assert_xpath(&output, r#"//div[@id="header"]//div[@id="toc"]"#, 1);

    // Titled _Table of Contents_.
    assert_xpath(
        &output,
        r#"//div[@id="toctitle"][text()="Table of Contents"]"#,
        1,
    );

    // Level 1 and level 2 titles only.
    assert_css(&output, r#"ul.sectlevel1"#, 1);
    assert_css(&output, r#"ul.sectlevel2"#, 1);
    assert_css(&output, r#"ul.sectlevel3"#, 0);
}

// The illustrative screenshot and the cross-references to the customization
// pages (title, levels, position) and the converter-support reference. Prose
// and links, nothing to render.
non_normative!(
    r#"
image::toc.png[Default table of contents,role=screenshot]

You can customize the xref:title.adoc[title of the TOC], the xref:levels.adoc[depth of the section levels], and the xref:position.adoc[position of the TOC in the document].
However, not all of the attributes are supported by all converters.
See xref:toc-ref.adoc[] for which attributes are available to each converter.

"#
);

// The `toc` attribute can be set outside the document too – Asciidoctor's CLI
// accepts `-a toc`. This crate's API analog is setting the attribute through
// `Options`; doing so activates the TOC for a document whose header does not
// set it, exactly as the header attribute entry does.
#[test]
fn toc_attribute_can_be_set_via_the_api() {
    verifies!(
        r#"
== Activate the TOC from the CLI

The `toc` attribute can also be specified via the command line (`-a toc`).

.TOC enabled via the CLI
 $ asciidoctor -a toc my-document.adoc
"#
    );

    let output = convert_with(
        WITHOUT_TOC,
        &Options::new().standalone(true).attribute("toc", ""),
    );
    assert_css(&output, r#"div#toc"#, 1);
    assert_xpath(&output, r#"//div[@id="header"]//div[@id="toc"]"#, 1);
}
